In [195]:
from datasets import load_dataset
import dspy
import openai
import os
import re
import pandas as pd
import ast
import json
from dotenv import load_dotenv
import numpy as np
import time

In [196]:
load_dotenv()

True

In [197]:

openai.api_key = os.getenv('OPENAI_API_KEY')
openai.organization = os.getenv('OPENAI_ORGANIZATION')

In [198]:
lm = dspy.LM('openrouter/anthropic/claude-3.5-sonnet', temperature=0, max_tokens=1024)
dspy.configure(lm=lm)

In [199]:
ds = pd.read_json('../data/train_dev_test_data/ner/fewnerd_sample_test.json', encoding_errors='replace')
ds = ds.to_dict('records')

In [200]:
ds[0]

{'id': 1,
 'text': 'In the early 1930s the band moved to the Grill Room of the Taft Hotel in New York ; the band was renamed ``George Hall and His Hotel Taft Orchestra``.',
 'label': [{'Grill Room': 'BUILDING'},
  {'Taft Hotel': 'BUILDING'},
  {'New York': 'LOCATION'},
  {'George Hall and His Hotel Taft Orchestra': 'ORGANIZATION'}],
 'dataset': 'few_nerd',
 'entity': ['Grill Room',
  'Taft Hotel',
  'New York',
  'George Hall and His Hotel Taft Orchestra']}

In [201]:
def remove_space(text):
    """Clean up spacing and formatting in dialogue text."""
    lines = text.split('\n')
    cleaned_lines = []
    
    for line in lines:
        # Remove multiple spaces
        cleaned = ' '.join(line.split())
        
        # Fix spacing around punctuation
        cleaned = re.sub(r'\s+([.,!?:;])', r'\1', cleaned)
        cleaned = re.sub(r'([.,!?:;])\s+', r'\1 ', cleaned)
        
        # Fix contractions
        cleaned = re.sub(r'\s*\'\s*s\b', "'s", cleaned)
        cleaned = re.sub(r'\s*n\s*\'\s*t\b', "n't", cleaned)
        cleaned = re.sub(r'\s*\'\s*ve\b', "'ve", cleaned)
        cleaned = re.sub(r'\s*\'\s*re\b', "'re", cleaned)
        cleaned = re.sub(r'\s*\'\s*ll\b', "'ll", cleaned)
        cleaned = re.sub(r'\s*\'\s*d\b', "'d", cleaned)
        cleaned = re.sub(r'\s*\'\s*m\b', "'m", cleaned)
        
        # Fix spaces around parentheses
        cleaned = re.sub(r'\(\s+', '(', cleaned)
        cleaned = re.sub(r'\s+\)', ')', cleaned)
        
        # Remove leading/trailing whitespace
        cleaned = cleaned.strip()
        
        cleaned_lines.append(cleaned)
        
    return '\n'.join(cleaned_lines)

In [202]:
examples = [
    dspy.Example({ 
                  "text" : str(r["text"]), 
                  "label": str(r['label'])
                }
                  ).with_inputs("text")
    
    for r in ds
    ]

In [203]:
example = examples[0]
for k, v in example.items():
    print(f"\n{k.upper()}:\n")
    print(v)

TEXT:

In the early 1930s the band moved to the Grill Room of the Taft Hotel in New York ; the band was renamed ``George Hall and His Hotel Taft Orchestra``.

LABEL:

[{'Grill Room': 'BUILDING'}, {'Taft Hotel': 'BUILDING'}, {'New York': 'LOCATION'}, {'George Hall and His Hotel Taft Orchestra': 'ORGANIZATION'}]

In [204]:
def calculate_f1_ent(gold_entities, predicted_entities):
    """
    Calculates the F1 score given the true labels and predicted labels.
    """
    # print("Input types:")
    # print(f"gold_entities type: {type(gold_entities)}")
    # print(f"predicted_entities type: {type(predicted_entities)}")
    
    if predicted_entities is None:
        return 0.0, 0.0, 0.0

    true_entities = {}
    pred_entities = {}
    
    # Convert to empty list if NaN
    def handle_nan(entities):
        # print(f"Handling NaN for: {type(entities)}")
        # If it's already a list, return it as is
        if isinstance(entities, list):
            return entities
        # Handle pandas/numpy types
        if isinstance(entities, (pd.Series, np.ndarray)):
            nan_check = pd.isna(entities)
            if isinstance(nan_check, (pd.Series, np.ndarray)):
                if nan_check.any():
                    return "[]"
            elif nan_check:
                return "[]"
        # Handle single values
        elif pd.isna(entities):
            return "[]"
        return entities

    # Handle NaN cases
    gold_entities = handle_nan(gold_entities)
    predicted_entities = handle_nan(predicted_entities)
            
    # Parse strings if needed
    if isinstance(gold_entities, str):
        gold_entities = ast.literal_eval(gold_entities)
    if isinstance(predicted_entities, str):
        predicted_entities = ast.literal_eval(predicted_entities)

    # Process gold entities
    # print(gold_entities)
    for entity in gold_entities:
        # print(entity)
        if isinstance(entity, str):
            entity = ast.literal_eval(entity)
        if entity.get('text') is not None:
            true_entities[entity["text"]] = entity['value']
        else:
            for key, value in entity.items():
                true_entities[key] = value
    
    # Process predicted entities
    for entity in predicted_entities:
        if isinstance(entity, str):
            entity = ast.literal_eval(entity)
        if entity.get('text') is not None:  
            pred_entities[entity['text']] = entity['value']
        else:
            for key, value in entity.items():
                pred_entities[key] = value

    # Calculate metrics
    true_positives = sum(1 for text in true_entities if text in pred_entities and true_entities[text] == pred_entities[text])
    false_positives = sum(1 for text in pred_entities if text not in true_entities)
    false_negatives = sum(1 for text in true_entities if text not in pred_entities)

    if true_positives == 0:
        return 0.0, 0.0, 0.0

    precision = true_positives / (true_positives + false_positives)
    recall = true_positives / (true_positives + false_negatives)
    f1_score = 2 * (precision * recall) / (precision + recall)

    return precision, recall, f1_score

In [205]:
def extract_prediction(pred):
    matches = re.findall(r"\[\{.*\}\]", pred)
    # print(matches)
    parsed_answer = matches[-1] if matches else ""
    if parsed_answer == "":
        return {}
    parsed_answer = ast.literal_eval(parsed_answer)
    return parsed_answer

In [206]:
def eval_metric(true, prediction, trace=None, provide_traceback=True):
    pred = prediction.label
    
    matches = re.findall(r"\[\{.*\}\]", pred)
    # print(matches)
    parsed_answer = matches[-1] if matches else ""
    if parsed_answer == "":
        return 0.0
    parsed_answer = ast.literal_eval(parsed_answer)
    # print(type(parsed_answer))
    gold_entities = ast.literal_eval(true.label)
    # print(parsed_answer)
    precision, recall, f1_score = calculate_f1_ent(gold_entities=gold_entities, predicted_entities= parsed_answer)
    return f1_score

In [225]:
from dspy.evaluate import Evaluate

evaluate = Evaluate(devset= examples, metric=eval_metric, num_threads=6, display_progress=True, display_table=10)

In [226]:
class Ent(dspy.Signature):
    """Extract named entities from the text. Possible entity type: ART, BUILDING, EVENT, LOCATION, ORGANIZATION, OTHER, PERSON, PRODUCT"""
    text = dspy.InputField()
    label = dspy.OutputField(desc='The list of named entities in the text: [{text: the text span, value: the entity label},]', prefix = 'Entities:')

In [221]:
class SimpleEnt(dspy.Module):
    def __init__(self, max_retries=3):
        super().__init__()
        self.prog = dspy.Predict(Ent)
        self.max_retries = max_retries

    def forward(self, text):
        return self.prog(text = text)
        # for attempt in range(self.max_retries):
        #     try:
        #         pred = self.prog(text=text)
                
        #         # Check if we got a valid response
        #         matches = re.findall(r"\[\{.*\}\]", pred.label)
        #         if matches:
        #             return pred
                    
        #     except Exception as e:
        #         print(f"Attempt {attempt + 1} failed: {str(e)}")
                
        #     if attempt < self.max_retries - 1:
        #         time.sleep(1)  # Wait before retrying
                
        # # If all retries failed, return empty prediction
        # return dspy.Prediction(label="[]")

In [227]:
simple_ent = SimpleEnt()

In [224]:
pred = simple_ent(text=example.text)
print("\nTEXT:\n")
print(example.text)

print("\nANSWER:\n")
print(example.label)
print("\nPREDICTION:\n")
print(pred)

TEXT:

In the early 1930s the band moved to the Grill Room of the Taft Hotel in New York ; the band was renamed ``George Hall and His Hotel Taft Orchestra``.

ANSWER:

[{'Grill Room': 'BUILDING'}, {'Taft Hotel': 'BUILDING'}, {'New York': 'LOCATION'}, {'George Hall and His Hotel Taft Orchestra': 'ORGANIZATION'}]

PREDICTION:

Prediction(
    label='[{"text": "Grill Room", "value": "BUILDING"}, {"text": "Taft Hotel", "value": "BUILDING"}, {"text": "New York", "value": "LOCATION"}, {"text": "George Hall", "value": "PERSON"}, {"text": "Hotel Taft Orchestra", "value": "ORGANIZATION"}]'
)

In [193]:
eval_metric(example, pred)

0.6666666666666665

In [228]:
evaluate = Evaluate(devset= examples, metric=eval_metric, num_threads=1, display_progress=True, display_table=10, return_outputs= True, return_all_scores=True, provide_traceback=True)
results = evaluate(simple_ent)
items = []
for sample in results[1]:

    item = {}
    sentence = sample[0]['text']
    label = sample[0]['label']
    if sample[1] == {}:
        pred = {}
    else:
        pred = sample[1]['label']
    item['text'] = sentence
    item['label'] = label
    item['pred'] = pred
    items.append(item)
df_result = pd.DataFrame(data = items)
df_result.to_csv('results/ner/claude-0shot-ner.csv')

Average Metric: 0.6666666666666665 / 1  (66.7):   0%|          | 0/251 [00:00<?, ?it/s]

Average Metric: 53.70863319686848 / 98  (54.8):  39%|███▉      | 98/251 [01:43<05:05,  2.00s/it] 2024-12-17T02:18:24.193627Z [error    ] Error for example in dev set: 		 litellm.RateLimitError: RateLimitError: OpenrouterException -
	with inputs:
		Example({'text': 'The Germans then attacked again and penetrated C Company, but the tanks of the North Irish Horse stopped the Germans until dusk.'}) (input_keys={'text'})

Stack trace:
	Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 761, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 5954, in convert_to_model_response_object
    raise raised_exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2108, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 175, in wrapped_program
    prediction = program(**example.inputs())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/primitives/program.py", line 23, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/10/sw0slq6565ddbg_lqxxhpqzh0000gn/T/ipykernel_43305/70903562.py", line 8, in forward
    return self.prog(text = text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 121, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 155, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs, _parse_values=self._parse_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 264, in v2_5_generate
    return adapter(
           ^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/adapters/base.py", line 19, in __call__
    outputs = lm(**inputs_, **lm_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 71, in __call__
    response = completion(ujson.dumps(dict(model=self.model, messages=messages, **kwargs)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 159, in cached_litellm_completion
    return litellm_completion(request, cache={"no-cache": False, "no-store": False})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 164, in litellm_completion
    return litellm.completion(cache=cache, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 1070, in wrapper
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 958, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2957, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2038, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenrouterException -
 [dspy.evaluate.evaluate] filename=evaluate.py lineno=196
Average Metric: 53.70863319686848 / 99  (54.3):  39%|███▉      | 99/251 [01:50<08:40,  3.43s/it]

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Average Metric: 54.70863319686848 / 101  (54.2):  40%|████      | 101/251 [01:59<09:11,  3.68s/it]2024-12-17T02:18:34.788415Z [error    ] Error for example in dev set: 		 litellm.RateLimitError: RateLimitError: OpenrouterException -
	with inputs:
		Example({'text': 'Malcolm III (; c.26 March 1031 \\u2013 13 November 1093 (age 62)) was King of Scots from 1058 to 1093.'}) (input_keys={'text'})

Stack trace:
	Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 761, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 5954, in convert_to_model_response_object
    raise raised_exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2108, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 175, in wrapped_program
    prediction = program(**example.inputs())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/primitives/program.py", line 23, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/10/sw0slq6565ddbg_lqxxhpqzh0000gn/T/ipykernel_43305/70903562.py", line 8, in forward
    return self.prog(text = text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 121, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 155, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs, _parse_values=self._parse_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 264, in v2_5_generate
    return adapter(
           ^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/adapters/base.py", line 19, in __call__
    outputs = lm(**inputs_, **lm_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 71, in __call__
    response = completion(ujson.dumps(dict(model=self.model, messages=messages, **kwargs)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 159, in cached_litellm_completion
    return litellm_completion(request, cache={"no-cache": False, "no-store": False})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 164, in litellm_completion
    return litellm.completion(cache=cache, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 1070, in wrapper
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 958, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2957, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2038, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenrouterException -
 [dspy.evaluate.evaluate] filename=evaluate.py lineno=196
Average Metric: 54.70863319686848 / 102  (53.6):  41%|████      | 102/251 [02:01<07:54,  3.18s/it]

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

2024-12-17T02:18:39.115374Z [error    ] Error for example in dev set: 		 litellm.RateLimitError: RateLimitError: OpenrouterException -
	with inputs:
		Example({'text': "He also appeared in and Raj Kanwar's action hit ``Jeet``."}) (input_keys={'text'})

Stack trace:
	Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 761, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 5954, in convert_to_model_response_object
    raise raised_exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2108, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 175, in wrapped_program
    prediction = program(**example.inputs())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/primitives/program.py", line 23, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/10/sw0slq6565ddbg_lqxxhpqzh0000gn/T/ipykernel_43305/70903562.py", line 8, in forward
    return self.prog(text = text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 121, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 155, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs, _parse_values=self._parse_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 264, in v2_5_generate
    return adapter(
           ^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/adapters/base.py", line 19, in __call__
    outputs = lm(**inputs_, **lm_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 71, in __call__
    response = completion(ujson.dumps(dict(model=self.model, messages=messages, **kwargs)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 159, in cached_litellm_completion
    return litellm_completion(request, cache={"no-cache": False, "no-store": False})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 164, in litellm_completion
    return litellm.completion(cache=cache, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 1070, in wrapper
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 958, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2957, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2038, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenrouterException -
 [dspy.evaluate.evaluate] filename=evaluate.py lineno=196
Average Metric: 54.70863319686848 / 103  (53.1):  41%|████      | 103/251 [02:05<08:41,  3.53s/it]

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Average Metric: 138.27848883143005 / 238  (58.1):  94%|█████████▍| 237/251 [03:56<00:10,  1.38it/s]2024-12-17T02:20:30.512917Z [error    ] Error for example in dev set: 		 litellm.RateLimitError: RateLimitError: OpenrouterException -
	with inputs:
		Example({'text': 'The Circinus Galaxy (ESO 97-G13) is a Seyfert galaxy in the constellation of Circinus.'}) (input_keys={'text'})

Stack trace:
	Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 761, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 5954, in convert_to_model_response_object
    raise raised_exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2108, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/evaluate/evaluate.py", line 175, in wrapped_program
    prediction = program(**example.inputs())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/primitives/program.py", line 23, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/10/sw0slq6565ddbg_lqxxhpqzh0000gn/T/ipykernel_43305/70903562.py", line 8, in forward
    return self.prog(text = text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 121, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 155, in forward
    completions = v2_5_generate(lm, config, signature, demos, kwargs, _parse_values=self._parse_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/predict/predict.py", line 264, in v2_5_generate
    return adapter(
           ^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/adapters/base.py", line 19, in __call__
    outputs = lm(**inputs_, **lm_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/utils/callback.py", line 202, in wrapper
    return fn(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 71, in __call__
    response = completion(ujson.dumps(dict(model=self.model, messages=messages, **kwargs)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 159, in cached_litellm_completion
    return litellm_completion(request, cache={"no-cache": False, "no-store": False})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/dspy/clients/lm.py", line 164, in litellm_completion
    return litellm.completion(cache=cache, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 1070, in wrapper
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/utils.py", line 958, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/main.py", line 2957, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/Users/hungcoreft/miniconda3/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2038, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: litellm.RateLimitError: RateLimitError: OpenrouterException -
 [dspy.evaluate.evaluate] filename=evaluate.py lineno=196
Average Metric: 138.27848883143005 / 239  (57.9):  95%|█████████▌| 239/251 [03:57<00:07,  1.67it/s]

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Average Metric: 147.69118724412846 / 251  (58.8): 100%|██████████| 251/251 [04:22<00:00,  1.05s/it]

In [238]:
def evaluate_modified_set(ds, program):
    examples = [
    dspy.Example({ 
                  "text" : remove_space(r["modified_text"]), 
                  "label": str(r['modified_label']),
                  "original_text": remove_space(r['original_text']),
                  "original_label": str(r['original_label']),
                  "index": r['index']
                #   "original_label": str(r['original_label'])
                }
                  ).with_inputs("text")
    
    for r in ds
    ]
    evaluate = Evaluate(devset= examples, metric=eval_metric, num_threads=1, display_progress=True, display_table=1, return_outputs= True, return_all_scores=True)
    results = evaluate(program)
    return results

In [239]:
class Ent(dspy.Signature):
    """Extract named entities from the text. Possible entity type: ART, BUILDING, EVENT, LOCATION, ORGANIZATION, OTHER, PERSON, PRODUCT"""
    text = dspy.InputField()
    label = dspy.OutputField(desc='The list of named entities in the text: [{"text": the text span, "value": the entity label},]', prefix = 'Entities:')

class SimpleEnt(dspy.Module):
    def __init__(self, max_retries=3):
        super().__init__()
        self.prog = dspy.Predict(Ent)
        self.max_retries = max_retries

    def forward(self, text):
        for attempt in range(self.max_retries):
            try:
                pred = self.prog(text=text)
                
                # Check if we got a valid response
                matches = re.findall(r"\[\{.*\}\]", pred.label)
                if matches:
                    return pred
                    
            except Exception as e:
                print(f"Attempt {attempt + 1} failed: {str(e)}")
                
            if attempt < self.max_retries - 1:
                time.sleep(1)  # Wait before retrying
                
        # If all retries failed, return empty prediction
        return dspy.Prediction(label="[]")

In [240]:
import glob
import difflib

In [241]:
# Configure GPT-4 as the language model
original_pred_ds = pd.read_csv('results/ner/claude-0shot-ner.csv', index_col=False)
original_pred_ds['text'] = original_pred_ds['text'].apply(lambda x: remove_space(x.encode('utf-8').decode('unicode-escape')))  # Replace 'your_function' with the actual function

# Get specific json files we want to process
json_files = glob.glob('../data/modified_data/ner/*_100.json')

for json_file in json_files:
    # Load the json file
    print(json_file)
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    results = evaluate_modified_set(data,simple_ent)

    # Convert results to dataframe
    items = []
    for sample in results[1]:
        item = {}
        sentence = sample[0]['text']
        label = sample[0]['label'] 
        # print(sample)
        if sample[1] == {}:
            pred = "[]"
        else:
            pred = sample[1]['label']
        item['text'] = sentence
        # print(label)
        # item['modified_label'] = [{entity['text']: entity['value']} for entity in label]
        item['modified_label'] = label
        pred = extract_prediction(pred)
        item['modified_pred'] = pred
        item['modified_pred'] = [{entity['text']: entity['value']} for entity in pred]
        original_text = sample[0]['original_text'].encode('utf-8').decode('unicode-escape')
        item['original_text'] = original_text
        index = sample[0]['index']
        # Find the best match for the original_text in the original_pred_ds['text'] using difflib
        matches = original_pred_ds['pred'].iloc[index] if index < len(original_pred_ds) else []
        item['original_pred'] = matches if matches else '[]'

        item['original_label'] = sample[0]['original_label']
        
        # Check if original_label is NaN and assign modified_label if it is
        if pd.isna(item['original_label']):
            item['original_label'] = item['modified_label']
            
        items.append(item)
    
    df_result = pd.DataFrame(data=items)
    
    # Save results with filename based on input json
    output_filename = f"results/ner/claude-0shot-{json_file.split('/')[-1].replace('.json', '')}.csv"
    df_result.to_csv(output_filename)

../data/modified_data/ner/casual_100.json
Average Metric: 42.259890109890115 / 70  (60.4):  75%|███████▌  | 69/92 [00:00<00:00, 1268.17it/s]

Average Metric: 49.81171083818142 / 92  (54.1): 100%|██████████| 92/92 [00:00<00:00, 960.68it/s]

../data/modified_data/ner/discourse_100.json
Average Metric: 41.47655122655122 / 72  (57.6): 100%|██████████| 72/72 [00:00<00:00, 1032.14it/s]

../data/modified_data/ner/compound_word_100.json
Average Metric: 50.03543417366944 / 86  (58.2): 100%|██████████| 86/86 [00:00<00:00, 1267.41it/s]

../data/modified_data/ner/temporal_bias_100.json
Average Metric: 55.25642984466513 / 91  (60.7): 100%|██████████| 91/91 [00:00<00:00, 1455.68it/s]

../data/modified_data/ner/coordinating_conjunction_100.json
Average Metric: 44.12049062049061 / 71  (62.1): 100%|██████████| 71/71 [00:00<00:00, 1436.11it/s]

../data/modified_data/ner/capitalization_100.json
Average Metric: 63.477497665732955 / 100  (63.5): 100%|██████████| 100/100 [00:03<00:00, 29.42it/s]

../data/modified_data/ner/dialectal_100.json
Average Metric: 56.826704014939295 / 99  (57.4): 100%|██████████| 99/99 [00:03<00:00, 29.91it/s]

../data/modified_data/ner/sentiment_100.json
Average Metric: 73.52099567099566 / 123  (59.8): 100%|██████████| 123/123 [00:13<00:00,  8.98it/s]

../data/modified_data/ner/grammatical_role_100.json
Average Metric: 56.77675396498925 / 91  (62.4): 100%|██████████| 91/91 [00:00<00:00, 1596.83it/s]

../data/modified_data/ner/length_bias_100.json
Average Metric: 49.81171083818142 / 92  (54.1): 100%|██████████| 92/92 [00:00<00:00, 1418.61it/s]

../data/modified_data/ner/concept_replacement_100.json
Average Metric: 49.7970588235294 / 85  (58.6): 100%|██████████| 85/85 [00:00<00:00, 1282.90it/s]

../data/modified_data/ner/typo_bias_100.json
Average Metric: 56.61263942455892 / 100  (56.6): 100%|██████████| 100/100 [00:08<00:00, 11.99it/s]

../data/modified_data/ner/geographical_bias_100.json
Average Metric: 91.36959064327483 / 134  (68.2): 100%|██████████| 134/134 [00:08<00:00, 15.21it/s]

../data/modified_data/ner/punctuation_100.json
Average Metric: 47.77478632478631 / 100  (47.8): 100%|██████████| 100/100 [00:15<00:00,  6.41it/s]

../data/modified_data/ner/derivation_100.json
Average Metric: 41.90166793990323 / 66  (63.5): 100%|██████████| 66/66 [03:22<00:00,  3.06s/it]

../data/modified_data/ner/active_to_passive_100.json
Average Metric: 49.452100840336115 / 81  (61.1): 100%|██████████| 81/81 [04:38<00:00,  3.44s/it]

../data/modified_data/ner/negation_100.json
Average Metric: 62.47589959060546 / 110  (56.8): 100%|██████████| 110/110 [06:09<00:00,  3.36s/it]

In [242]:
from scipy import stats

In [243]:
result_files = glob.glob('results/ner/claude-0shot-*_100.csv')

aggregated_results = []

def convert_string_to_entities(entity_str):
    """Convert string representation of entities to proper format"""
    if isinstance(entity_str, str):
        try:
            # Convert string to list of dicts
            entities = ast.literal_eval(entity_str)
            # Handle nested lists by flattening
            if isinstance(entities, list):
                # Handle double nested lists
                if len(entities) > 0 and isinstance(entities[0], list):
                    entities = entities[0]
                # Handle list of dicts with text/value format
                if len(entities) > 0 and isinstance(entities[0], dict):
                    if 'text' in entities[0]:
                        return entities
                    # Handle list of single-key dicts
                    if all(len(e) == 1 for e in entities):
                        converted = []
                        for e in entities:
                            for text, value in e.items():
                                converted.append({'text': text, 'value': value})
                        return converted
            return entities
        except:
            return []
    return entity_str

for file in result_files:
    # Extract modification type from filename
    mod_type = file.split('-')[-1].replace('.csv','')
    print(mod_type)
    # Read results file
    df = pd.read_csv(file)

    # Calculate F1 scores row by row
    original_f1_scores = []
    modified_f1_scores = []
    original_precision_scores = []
    original_recall_scores = []
    modified_precision_scores = []
    modified_recall_scores = []

    for idx, row in df.iterrows():
        # Convert string representations to proper format
        original_label = convert_string_to_entities(row['original_label'])
        original_pred = convert_string_to_entities(row['original_pred'])
        modified_label = convert_string_to_entities(row['modified_label'])
        modified_pred = convert_string_to_entities(row['modified_pred'])

        # Calculate F1 for original
        o_precision, o_recall, o_f1 = calculate_f1_ent(original_label, original_pred)
        original_f1_scores.append(o_f1)
        original_precision_scores.append(o_precision)
        original_recall_scores.append(o_recall)

        # Calculate F1 for modified
        m_precision, m_recall, m_f1 = calculate_f1_ent(modified_label, modified_pred)
        modified_f1_scores.append(m_f1)
        modified_precision_scores.append(m_precision)
        modified_recall_scores.append(m_recall)

    # Take averages
    original_f1 = sum(original_f1_scores) / len(original_f1_scores) if original_f1_scores else 0
    modified_f1 = sum(modified_f1_scores) / len(modified_f1_scores) if modified_f1_scores else 0
    original_precision = sum(original_precision_scores) / len(original_precision_scores) if original_precision_scores else 0
    original_recall = sum(original_recall_scores) / len(original_recall_scores) if original_recall_scores else 0
    modified_precision = sum(modified_precision_scores) / len(modified_precision_scores) if modified_precision_scores else 0
    modified_recall = sum(modified_recall_scores) / len(modified_recall_scores) if modified_recall_scores else 0
    
    # Calculate the difference between original and modified F1 scores
    difference = -round(original_f1 - modified_f1, 2)
    
    # Calculate percentage difference with respect to original F1
    pct_difference = -round((original_f1 - modified_f1) / original_f1 * 100, 2) if original_f1 != 0 else 0
    
    # Perform t-test between original and modified predictions
    t_stat, p_value = stats.ttest_ind(
        (df['original_pred'] == df['original_label']).astype(float),
        (df['modified_pred'] == df['modified_label']).astype(float)
    )
    
    aggregated_results.append({
        'task': 'named_entity_recognition',
        'modification': mod_type,
        'original_res': round(original_f1, 2),
        'modified_res': round(modified_f1, 2),
        'difference': difference,  # Difference in F1 score
        'pct_difference': pct_difference,  # Percentage difference relative to original F1
        'p_value': p_value,  # Add p-value from t-test
        'original_precision': round(original_precision, 2),
        'original_recall': round(original_recall, 2),
        'modified_precision': round(modified_precision, 2), 
        'modified_recall': round(modified_recall, 2)
    })

# Create final results dataframe
results_df = pd.DataFrame(aggregated_results)

# Sort the results based on modification_name
modification_name = ['temporal_bias_100', 'geographical_bias_100','length_bias_100', 'typo_bias_100', 'capitalization_100', 'punctuation_100', 'derivation_100', 'compound_word_100','active_to_passive_100','grammatical_role_100', 'coordinating_conjunction_100', 'concept_replacement_100','negation_100','discourse_100','sentiment_100','casual_100', 'dialectal_100']
results_df['modification'] = pd.Categorical(results_df['modification'], categories=modification_name, ordered=True)
results_df = results_df.sort_values(by='modification')

# Calculate averages across all modifications
avg_original = results_df['original_res'].mean()
avg_modified = results_df['modified_res'].mean()
avg_difference = avg_original - avg_modified
avg_pct_difference = results_df['pct_difference'].mean()
avg_orig_precision = results_df['original_precision'].mean()
avg_orig_recall = results_df['original_recall'].mean()
avg_mod_precision = results_df['modified_precision'].mean()
avg_mod_recall = results_df['modified_recall'].mean()

# Add averages as a new row
results_df.loc[len(results_df)] = {
    'task': 'named_entity_recognition',
    'modification': 'average',
    'original_res': round(avg_original, 2),
    'modified_res': round(avg_modified, 2),
    'difference': -round(avg_difference, 2),
    'pct_difference': round(avg_pct_difference, 2),
    'p_value': None,  # No p-value for average row
    'original_precision': round(avg_orig_precision, 2),
    'original_recall': round(avg_orig_recall, 2),
    'modified_precision': round(avg_mod_precision, 2),
    'modified_recall': round(avg_mod_recall, 2)
}

print("\n")
results_df.to_csv('results/ner/claude-DP.csv')

# Apply styling to highlight rows where original_res > modified_res and significant p-values
def highlight_drops_and_significance(row):
    colors = [''] * len(row)
    if row['original_res'] > row['modified_res']:
        colors = ['background-color: red'] * len(row)
        # If p-value < 0.05, add bold text
        if 'p_value' in row and row['p_value'] is not None and row['p_value'] < 0.05:
            colors = ['background-color: red; font-weight: bold'] * len(row)
    return colors

results_df.round(2).style.apply(highlight_drops_and_significance, axis=1)

casual_100
punctuation_100
sentiment_100
geographical_bias_100
length_bias_100
grammatical_role_100
compound_word_100
capitalization_100
active_to_passive_100
temporal_bias_100
typo_bias_100
coordinating_conjunction_100
dialectal_100
concept_replacement_100
derivation_100
negation_100
discourse_100

/var/folders/10/sw0slq6565ddbg_lqxxhpqzh0000gn/T/ipykernel_43305/2020721611.py:119: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df.loc[len(results_df)] = {